### PR TITLE
Add documentation for Markdown settings

### PR DESCRIPTION
**Pull request by pascalberger**
Add documentation for Markdown settings and how to enable Markdown extensions

Fixes remaining open parts of https://github.com/statiqdev/Statiq.Framework/issues/222

### CODE REVIEW

**Comment by daveaglick** [comment]
This is great, thanks! I _really_ need to do a better job of documenting these features as I add them.

**Comment by pascalberger** [comment]
@daveaglick Something seems to have gone wrong in the force push, since it now basically undid #65. Let me know if I should repush original changes.

**Comment by daveaglick** [comment]
Huh - I probably just missed it during the interactive rebase. There was a weird conflict that GitHub seemed like it could resolve, but then didn't. Yeah, if you don't mind putting it in one more time I'll do a quick approval.

Trying (again) to start getting on top of things - your PRs in docs and the theme are next up. Thanks!

**Comment by pascalberger** [comment]
@daveaglick I created #67 to bring the lost stuff back in

**Pull request merged**
